backend:
  name: git-gateway
  branch: master

# publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/writing"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template",
          name: "templateKey",
          widget: "select",
          options: ["blog-post"],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Stylesheet", name: "stylesheet", widget: "string" }
      - {
          label: "Tags",
          name: "tags",
          widget: "select",
          multiple: true,
          options:
            [
              "conferences",
              "learning",
              "essay",
              "long-form",
              "workplace-guides",
              "css",
              "javascript",
              "command-line",
              "ios",
              "goals",
              "archived",
              "creative-writing",
            ],
        }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/work/index.md"
        label: "Work Page"
        name: "work"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "work-page",
            }
          - {
              label: "Title",
              name: "title",
              widget: "hidden",
              default: "work-page",
            }
          - {
              label: "Project 1",
              name: project1,
              url: string,
              widget: object,
              fields:
                [
                  {
                    label: Image,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Background,
                    name: background1,
                    widget: select,
                    options: ["red", "white", "off-white"],
                  },
                ],
            }
          - {
              label: "Project 2",
              name: project2,
              url: string,
              widget: object,
              fields:
                [
                  {
                    label: Image,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Background,
                    name: background2,
                    widget: select,
                    options: ["red", "white", "off-white"],
                  },
                ],
            }
          - {
              label: "Project 3",
              name: project3,
              url: string,
              widget: object,
              fields:
                [
                  {
                    label: Image,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Background,
                    name: background3,
                    widget: select,
                    options: ["red", "white", "off-white"],
                  },
                ],
            }
          - {
              label: "Project 4",
              name: project4,
              url: string,
              widget: object,
              fields:
                [
                  {
                    label: Image,
                    name: image4,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Background,
                    name: background4,
                    widget: select,
                    options: ["red", "white", "off-white"],
                  },
                ],
            }
          - {
              label: "Project 5",
              name: project5,
              url: string,
              widget: object,
              fields:
                [
                  {
                    label: Image,
                    name: image5,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Background,
                    name: background5,
                    widget: select,
                    options: ["red", "white", "off-white"],
                  },
                ],
            }
          - {
              label: "Project 6",
              name: project6,
              url: string,
              widget: object,
              fields:
                [
                  {
                    label: Image,
                    name: image6,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Background,
                    name: background6,
                    widget: select,
                    options: ["red", "white", "off-white"],
                  },
                ],
            }
          - {
              label: "Project 7",
              name: project7,
              url: string,
              widget: object,
              fields:
                [
                  {
                    label: Image,
                    name: image7,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Background,
                    name: background7,
                    widget: select,
                    options: ["red", "white", "off-white"],
                  },
                ],
            }
          - { label: "Reel", name: "reel", widget: "markdown" }
      - file: "src/pages/index.md"
        label: "Index Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: "Title",
              name: "title",
              widget: "hidden",
              default: "Index Page",
            }
          - { label: "Intro 1", name: intro1, widget: "markdown" }
          - { label: "Intro 2", name: intro2, widget: "markdown" }
          - { label: "Intro 3", name: intro3, widget: "markdown" }
          - {
              label: "Headshots",
              name: helenHeadshots,
              widget: object,
              fields:
                [
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "product-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - { label: Full_image, name: full_image, widget: image }
